# Generated by Django 4.0.6 on 2022-08-22 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Appointment', 'Appointment'), ('Operation', 'Operation'), ('Admitted', 'Admitted'), ('Discharged', 'Discharged'), ('Reports', 'Reports')], default='NA', max_length=11)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('NA', 'NA')], default='NA', max_length=3)),
                ('disease', models.CharField(blank=True, max_length=50)),
                ('has_allergies', models.BooleanField(default=False)),
                ('allergies', models.TextField(blank=True)),
                ('has_medical_history', models.BooleanField(default=False)),
                ('medical_history', models.TextField(blank=True)),
                ('advised_procedure', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_process', to='patients.procedure')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
