# Generated by Django 4.0.6 on 2022-08-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patientprofile_advised_procedure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='procedure',
            name='name',
            field=models.CharField(choices=[('Appointment', 'Appointment'), ('Operation', 'Operation'), ('Admitted', 'Admitted'), ('Discharged', 'Discharged'), ('Reports', 'Reports'), ('Registered', 'Registered')], default='NA', max_length=11),
        ),
    ]
