# Generated by Django 4.0.6 on 2022-08-23 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_timeslots_remove_appointment_timeslot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='timeslot',
        ),
        migrations.AddField(
            model_name='appointment',
            name='timeslot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot', to='patients.timeslots'),
        ),
    ]
