# Generated by Django 4.0.6 on 2022-08-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_remove_appointment_doctor_appointment_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'SCHEDULED'), ('RESCHEDULE', 'RESCHEDULE'), ('CANCELLED', 'CANCELLED')], default='SCHEDULED', max_length=10),
        ),
    ]
