# Generated by Django 4.0.6 on 2022-08-29 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_medication_alter_appointment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='medication',
        ),
        migrations.AddField(
            model_name='medication',
            name='prescription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Medication', to='patients.prescription'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='name',
            field=models.CharField(choices=[('Operation', 'Operation'), ('Admitted', 'Admitted'), ('Discharged', 'Discharged'), ('Reports', 'Reports'), ('Registered', 'Registered')], default='NA', max_length=11),
        ),
    ]
