# Generated by Django 4.0.6 on 2022-08-31 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_prescription_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedure',
            name='status',
        ),
        migrations.AlterField(
            model_name='procedure',
            name='name',
            field=models.CharField(choices=[('Operation', 'Operation'), ('Admitted', 'Admitted'), ('Medication', 'Medication'), ('Discharged', 'Discharged'), ('Reports', 'Reports'), ('Registered', 'Registered')], default='NA', max_length=11),
        ),
    ]
