# Generated by Django 4.0.6 on 2022-08-31 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_remove_procedure_status_alter_procedure_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
