# Generated by Django 4.0.6 on 2022-08-31 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_alter_procedure_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='advised_procedure',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='advise',
            field=models.CharField(choices=[('Operation', 'Operation'), ('Admitted', 'Admitted'), ('Medication', 'Medication'), ('Discharged', 'Discharged'), ('Reports', 'Reports')], default='NA', max_length=50),
        ),
    ]
