# Generated by Django 4.0.6 on 2022-08-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=11)),
                ('birthdate', models.DateTimeField(verbose_name='DOB')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=6)),
                ('role', models.CharField(choices=[('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Surgeon', 'Surgeon'), ('Receptionist', 'Receptionist'), ('Patient', 'Patient')], max_length=12)),
                ('joining_date', models.DateTimeField(blank=True, null=True)),
                ('termination_date', models.DateTimeField(blank=True, null=True)),
                ('is_doctor', models.BooleanField(default=False)),
                ('is_surgeon', models.BooleanField(default=False)),
                ('is_nurse', models.BooleanField(default=False)),
                ('is_receptionist', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_patient', models.BooleanField(default=False)),
                ('qualifications', models.CharField(blank=True, max_length=200, null=True)),
                ('speciality', models.CharField(blank=True, max_length=200, null=True)),
                ('experiance_in_years', models.IntegerField(blank=True, null=True, verbose_name='Experiance(in yrs)')),
                ('leaves_taken', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
