# Generated by Django 4.0.6 on 2022-08-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_joining_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Surgeon', 'Surgeon'), ('Receptionist', 'Receptionist'), ('Patient', 'Patient'), ('Admin', 'Admin')], max_length=12),
        ),
    ]
