# Generated by Django 4.0.6 on 2022-08-05 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_shifts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shifts',
            name='date',
        ),
    ]
