# Generated by Django 4.0.6 on 2022-08-05 11:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_shifts_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifts',
            name='allocated_shift',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1),
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='Room Name')),
                ('type', models.CharField(blank=True, choices=[('General', 'General'), ('Special', 'Special')], max_length=7, null=True)),
                ('no_of_beds', models.IntegerField()),
                ('assigned_nurses', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
