# Generated by Django 4.0.6 on 2022-08-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_shifts_allocated_shift_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='name',
            field=models.CharField(max_length=5),
        ),
    ]
