# Generated by Django 4.0.6 on 2022-08-16 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_leaverequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'ordering': ['-from_date', 'applied_on']},
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='applied_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_date', models.DateField()),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='shift_to_substitute', to='account.shifts')),
                ('substitute', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='substitute_employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
