# Generated by Django 4.0.6 on 2022-08-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_leaverequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='has_substitute',
            field=models.BooleanField(default=False),
        ),
    ]
