# Generated by Django 4.0.6 on 2022-08-31 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_leaverequest_has_substitute'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
