# Generated by Django 4.0.6 on 2022-09-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_operation_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
