# Generated by Django 4.0.6 on 2022-09-02 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_bed_is_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='name',
            new_name='operation-name',
        ),
    ]
