# Generated by Django 4.0.6 on 2022-09-06 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0004_rename_name_operation_operation-name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_time', models.TimeField()),
                ('is_medication_provided', models.BooleanField(default=False)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_visit', to=settings.AUTH_USER_MODEL)),
                ('surgeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advised_by_doctor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorsVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_normal', models.BooleanField()),
                ('visit_time', models.TimeField()),
                ('is_visit_done', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_on_visit', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_to_visit', to=settings.AUTH_USER_MODEL)),
                ('surgeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_doctor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
