# Generated by Django 4.0.6 on 2022-09-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_nursevisit_doctorsvisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorsvisit',
            name='is_visit_done',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='doctorsvisit',
            name='visit_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='nursevisit',
            name='medication_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
