# Generated by Django 4.0.6 on 2022-09-09 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_charge', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('surgery_charge', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('admission_charge', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('opd_charge', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_charge', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('date', models.DateField(auto_now_add=True)),
                ('bill_details', models.JSONField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
